stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - artifacts/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - artifacts/raw
    outs:
      - artifacts/processed

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - artifacts/processed
    outs:
      - artifacts/model
      - artifacts/model_checkpoint
      - artifacts/weights
